name: builds

on: push

jobs:
  build:
    name: Build Programs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: 'experimental-features = nix-command flakes'
    - uses: cachix/cachix-action@v8
      with:
        name: ssbm-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run nix flake check
      run: nix flake check
    - name: Build Wiimm's Iso Tools
      run: nix build -L .#wiimms-iso-tools
    - name: Build Slippi Netplay
      run: nix build -L .#slippi-netplay
    - name: Build Slippi Playback
      run: nix build -L .#slippi-playback
    - name: Build Gecko Tools
      run: nix build -L .#gecko
    - name: Build PowerPC-EABI-Assembling
      run: nix build -L .#powerpc-eabi-assembling
    - name: Build GCMTool
      run: nix build -L .#gcmtool
      continue-on-error: true

