name: builds

on: push

jobs:
  build:
    name: Build Programs
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: ssbm-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run nix flake check
      run: |
        nix flake check --experimental-features 'flakes nix-command'
    - name: Build Wiimm's Iso Tools
      run: nix build -L .#wiimms-iso-tools
    - name: Build Slippi Netplay
      run: nix build -L .#slippi-netplay
    - name: Build Slippi Playback
      run: nix build -L .#slippi-playback
    - name: Build Gecko Tools
      run: nix build -L .#gecko
    - name: Build PowerPC-EABI-Assembling
      run: nix build -L .#powerpc-eabi-assembling
    - name: Build GCMTool
      run: nix build -L .#gcmtool
